---
title: "Untitled"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
---



```{r include=FALSE}

## To clear your environment
remove(list = ls())

library(dplyr)
library(tidyr)
library(stringr)
library(rstatix)
library(rlang)

library(meta)

library(cowplot)
library(rcartocolor)
library(RColorBrewer)
library(ggpubr)


source('./code/func_plot_ma.R')
source('./code/func_color_bygroup.R')
source('./code/func_comparing_means_Dunns.R')


dir.fig <- "./figures/"
##' an extra post fix for figure's version control
vv <- ""
today <- format(Sys.time(), "%Y%m%d")
```


####  - comparing means - difference among groups

Summary
  Use a t-test for comparing means of normally distributed data.
  Use a Wilcoxon test for non-parametric data.
  Use a Chi-square test for categorical data.
  Use a paired t-test if the data points are related or paired.
  
```{r - data}

f <- './data/data_ma_result_each.RDS'
ma_result_each <- readRDS(f)


subgroups <- c(
  'subgroup_design', 'exposure_o2',
  'nature_type_o2',
  'Region',
  'Season',
  'density_class',
  'age_group', 'gender_group', 'duration_group') %>%  sort()

ind_sub_levels <- c(
  ## // negative aspect
  "TMD", 
  "Anxiety",            # POMS / STAI
  "Fatigue", "Confusion", "Anger", 
  "Depression",         # --- POMS
  "Stress",             # PSS
  "Negative Affect",    # PANAS
  
  ## // positive aspect 
  "Positive Affect",
  "Restorative Effect", # ROS
  "Vigor",              # --- POMS
  "Vitality"            # SVS
)

```



```{r - loop run}

for (subgroup_select in subgroups) {
  
  ma_result_each_i <- ma_result_each  %>%
    dplyr::mutate(ind_sub = factor(ind_sub, levels = ind_sub_levels)) %>%
    # dplyr::filter(tool == 'PANAS') %>%
    # dplyr::filter(ind_sub == 'Negative Affect') %>%
    dplyr::filter(group_name == subgroup_select) %>%
    dplyr::filter(!stringr::str_detect(pattern = ";|from window|residential|participatory", string = subgroup)) %>%
    dplyr::mutate(subgroup = gsub('L4 - | in nature|L5 - nature ', '', subgroup))
  
  ##' Use factor to keep consistent order of the groups
  ##' 1. decide factor levels, and color scheme 
  if(subgroup_select == 'nature_type_o2'){
    group_title = str_to_sentence(gsub('_|_o2', ' ', subgroup_select)) %>% trimws()
    color_bygroup = nature_type_color; 
    group_list = nature_type_list
  } else if(subgroup_select == 'age_group'){
    group_title = str_to_sentence(gsub('_', ' ', subgroup_select))
    color_bygroup = age_group_color;
    group_list = age_group_list
  } else if(subgroup_select == 'density_class'){
    group_title = 'Urban density'
    main_cat = c('Low density', 'Medium density', 'High density')
    mixed_cat = unique(ma_result_each_i$subgroup) %>% sort()
    group_list = c(main_cat, unique(mixed_cat[!(mixed_cat %in% main_cat)]))
    color_bygroup = func_color_bygroup(df = ma_result_each_i, column_name = 'subgroup') 
  } else if(subgroup_select == 'gender_group'){
    group_title = str_to_sentence(gsub('_', ' ', subgroup_select))
    color_bygroup = gender_group_color;
    group_list = gender_group_list
  } else if(subgroup_select == 'duration_group'){
    group_title = 'Duration in nature (minutes)'
    color_bygroup = duration_group_color; 
    group_list = duration_group_list
  } else if(subgroup_select == 'Season'){
    group_title = str_to_sentence(gsub('_|_o2', ' ', subgroup_select)) %>% trimws()
    main_seasons = c('Spring', 'Summer', 'Fall', 'Winter')
    mixed_season = unique(ma_result_each_i$subgroup) %>% sort()
    group_list = c(main_seasons, unique(mixed_season[!(mixed_season %in% main_seasons)]))
    color_bygroup = func_color_bygroup(df = ma_result_each_i, column_name = 'subgroup') 
  } else if(subgroup_select == 'Region'){
    group_title = subgroup_select
    color_bygroup = region_color;
    group_list = region_list
  } else {
    # next
    group_title = str_to_sentence(gsub('_|_o2', ' ', subgroup_select)) %>% trimws()
    group_list = unique(ma_result_each_i$subgroup) %>% sort()
    color_bygroup = func_color_bygroup(df = ma_result_each_i, column_name = 'subgroup')
  }
  
  ##' 2. modify the factor levels
  # group_list <- unique(ma_result_each_i$subgroup) %>% sort()
  ma_result_each_i <- ma_result_each_i %>%
    dplyr::mutate(subgroup = factor(x = subgroup, levels = group_list))
  

  ## run 2 -- an updated function 
  which_test = 'dunn'
  func_test_dif_dunn2(df = ma_result_each_i, value = 'SMD', group = 'subgroup', 
                      which_test, ## "dunn" or "wilcoxon",
                      facet_by = 'ind_sub')
  fname <- paste0(dir.fig, paste('es_comb_subgroup', subgroup_select, 'TestDiff', today, which_test, vv, sep = '_'), '.png');
  print(fname)
  func_ggsave(fname, w = 7, h = 6, save_png = T)
}

```

  